name: Deploy

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: 'Выберите окружение'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Версия для деплоя'
        required: false
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build for deploy
      run: npm run build
    - name: Деплой на ${{ github.event.inputs.environment }}
      run: |
        echo "Деплоим версию ${{ github.event.inputs.version }} на ${{ github.event.inputs.environment }}"
        # Здесь можно добавить реальные команды деплоя
        # Например: 
        # if [ "${{ github.event.inputs.environment }}" == "production" ]; then
        #   npm run deploy:prod
        # else
        #   npm run deploy:staging
<<<<<<< HEAD
        # fi
=======
        # fi
>>>>>>> 1729457 (SPRINT-1: actions)
